# Generated by Django 4.2.1 on 2023-05-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vater',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('gehalt', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Einkommen')),
            ],
            options={
                'verbose_name': 'Vater',
                'verbose_name_plural': 'Väter',
            },
        ),
    ]
