# Generated by Django 4.2.1 on 2023-05-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_mutter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Kind')),
                ('noten', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Schulnoten')),
                ('mutter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.mutter', verbose_name='Mutter')),
            ],
            options={
                'verbose_name': 'Kind',
                'verbose_name_plural': 'Kinder',
            },
        ),
    ]
